repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: destroyed-symlinks
  - id: check-symlinks
  - id: check-case-conflict
  rev: v5.0.0
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  hooks:
  - id: yamlfmt
    exclude: base_data/
    args:
    - --width
    - '120'
    - --implicit_start
    - --implicit_end
    - --mapping
    - '2'
    - --sequence
    - '2'
    - --offset
    - '0'
  rev: 0.2.3
ci:
  autoupdate_schedule: quarterly
